//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PjSua2.Native.pjsua2 {

public enum pjmedia_vid_dev_hwnd_type {
  PJMEDIA_VID_DEV_HWND_TYPE_NONE,
  PJMEDIA_VID_DEV_HWND_TYPE_WINDOWS,
  PJMEDIA_VID_DEV_HWND_TYPE_COCOA,
  PJMEDIA_VID_DEV_HWND_TYPE_IOS,
  PJMEDIA_VID_DEV_HWND_TYPE_ANDROID
}

}
