//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PjSua2.Native.pjsua2 {

public enum pjsua_sip_siprec_use {
  PJSUA_SIP_SIPREC_INACTIVE,
  PJSUA_SIP_SIPREC_OPTIONAL,
  PJSUA_SIP_SIPREC_MANDATORY
}

}
